### ISSUE TITLE
support ElasticSearch Shield

### ISSUE THREAD

**Issue by jayhilden** [elmahio/Elmah.Io.ElasticSearch#35]
suggested priv setup:
```
# Elmah
elmah:
  indices:
    'elmah':
      privileges: read, index, indices:admin/get, indices:admin/exists, indices:admin/mapping/put, create_index
```
